### ISSUE TITLE
Static large objects fail MD5SUM check on download

### ISSUE THREAD

**Issue by ncw** [ncw/swift#67]
Checking MD5SUMs when downloading a static large object doesn't work.

The library should be checking for `X-Static-Large-Object: True` and disabling the check - swift doesn't seem to be putting the `X-Object-Manifest` on like it used to for dynamic large objects.

**Comment by hfat** [comment]
Thanks for fixing this bug.
But shouldn't the library ideally retrieve the correct sum and check it? Or verify each segment before assembling the file?

Disabling the check would of course be better than the current behavior but if retrieving the correct sum(s) isn't possible, perhaps the user should be notified (for instance with a non-fatal error). The expectation would naturally be that that the software has verified the sum upon completion of the download since that's what it does with other files.
Or if the verification is basically useless to begin with, pehaps it should be disabled by default so as not to waste resources and induce a false sense of security.

**Comment by ncw** [comment]
@hfat Unfortunately it isn't possible to retreive the MD5SUM for a chunked file.  You can get the MD5SUM of the MD5SUMs of the individual segments.  However that isn't at all easy to calculate for the receiver, so my preference is to just ignore the check for big files.  The library has been doing that for Dynamic large objects for some time, it just needs a tweak to do the same thing for static large objects.

**Comment by hfat** [comment]
In case you mention that in the documentation, note that it's not only big files that are affected but (at least with Hubic's official Linux client) all segmented files, which can be quite small.
